# Generated by Django 5.0.6 on 2024-05-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_contacts_userprofile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_email',
        ),
    ]
