# Generated by Django 5.0.6 on 2024-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseitem',
            name='file',
            field=models.FileField(default=1, upload_to='course/'),
            preserve_default=False,
        ),
    ]
