# Generated by Django 5.0.6 on 2024-05-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_categorymodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesmodel',
            name='level',
            field=models.CharField(choices=[('Any', 'Any'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=100),
        ),
    ]
