# Generated by Django 5.0.6 on 2024-05-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseitem_description_courseitem_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseitem',
            old_name='file',
            new_name='course_file',
        ),
    ]
