# Generated by Django 5.0.6 on 2024-05-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursesmodel_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesmodel',
            name='owner_profile',
        ),
    ]
