# Generated by Django 5.0.6 on 2024-05-19 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursesmodel_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesmodel',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseitem'),
        ),
    ]
