# Generated by Django 5.0.6 on 2024-05-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_coursesmodel_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesmodel',
            name='courses',
        ),
    ]
