# Generated by Django 5.0.6 on 2024-05-19 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_coursesmodel_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseitem',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='courses.coursesmodel'),
        ),
    ]
