# Generated by Django 5.0.6 on 2024-05-19 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courseitem_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_file', models.FileField(upload_to='course/')),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_item', to='courses.coursesmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseItem',
        ),
    ]
